Prac1_voting/pracProject/myapp/urls.py
from django.urls import path
from .views import detail,index, result,vote

app_name= 'myapp'

urlpatterns = [
    path('',index, name='index'),
    path('detail/<int:question_id>',detail, name='detail'),
    path('result/<int:question_id>',result, name='result'),     #<>는 변수의미
    path('vote/<int:question_id>',vote, name='vote'),
]

Prac1_voting/pracProject/pracProject/urls.py
from django.contrib import admin
from django.urls import path, include

# include에 app_name 형태를 쓰지말고
# 앱의 urls.py 파일 내에 변수 app_name을 정의하면 그것이 namespace 역할을 하게 된다.
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls'))
]

Prac1_voting/pracProject/myapp/models.py
from django.db import models

class Question(models.Model):
    question_text= models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

# Question모델(테이블)에는 최대 길이가 200이고, character type으로 채워질 question_text필드가 있고,
# dateTime type이고 설명이 date published인 pub_date라는 필드가 있다.


class Choice(models.Model):
    question= models.ForeignKey(Question, on_delete= models.CASCADE)
    choice_text= models.CharField(max_length=200)
    votes= models.IntegerField(default=0)
    
# Choice모델에는 Question모델을 참조하는 ForeignKey가 있고, 
# 최대 길이가 200이고 character type인 choice_text필드와,
# 기본값이 0이고 integer type인 votes필드가 있다.

Prac1_voting/pracProject/myapp/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from .models import Question, Choice    #모델 import

def index(request):
    #index view요청이 오면 역순(-)으로 5개 까지만 정렬하고 latest_question_list에 저장
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'index.html', context)

def detail(request, question_id):
    #  get_object_or_404로 해당 Question 모델을 찾고, 템플릿으로 전해주고있다.
    question= get_object_or_404(Question, pk=question_id)
    return render(request, 'detail.html', {'question': question})

def result(request,question_id):
    question= get_object_or_404(Question, pk=question_id)
    return render(request,'result.html',{'question':question})

def vote(request, question_id):
    question=get_object_or_404(Question,pk=question_id)
    try:
        #request.POST['변수이름']: 전달받은 변수의 값들을 확인 할 수 있다.
        # html form에서 post요청-> get(): ()안 조건 받아와-> post로 넘어온 choice값으로 선택된 항목(choice)을 넣기
        selected_choice= question.choice_set.get(pk=request.POST['choice']) #(detail.html에 choice변수)
    #예외가 발생했을 시에 question 모델과 에러 메세지를 template에 전달
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'detail.html',{'question':question, 'error_message':"쉣",})
    else:
        # choice를 잘 얻어왔으면 투표 수를 1증가-> result창으로 이동
        selected_choice.votes +=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('myapp:result', args=(question.id,)))

Prac1_voting/pracProject/myapp/templates/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <!-- 질문 제목 txt로 불러오기 -->
    <h1>{{question.question_text}}</h1>
    <!-- 에러메세지 -->
    {% if error_message %}
    <p><strong>{{error_message}}</strong></p>
    {% endif %}

    <form action="{% url 'myapp:vote' question.id %}" method="post">
        <!-- CSRF공격 막기: 서버로 들어온 요청이 사이트 내부에서 온 것이 맞는지 -->
        {% csrf_token %}
        <!-- question.choice_set.all은 해당 Question모델을 foreign key로 참조하는 모든 Choice 모델을 가져온다 -->
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}" />
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br />
        <!-- forloop은 반복문의 반복횟수 출력(1부터 시작) -->
        {% endfor %}
        <input type="submit" value="Vote" />

    </form>


</body>

</html>

Prac1_voting/pracProject/myapp/templates/detail1(완성전).html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>detail</title>
</head>

<body>
    <h1>{{question.question_text}}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}}</li>
        {% endfor %}
    </ul>
    <!-- for 반복: 제목을txt로 반복 -->
    <!--  question.choice_set.all은 Python 코드의 question.choice_set.all() 함수와 동일하며, for 문을 간편하게 쓰기 위해 존재한다.
 이는 해당 Question 모델을 foreign key로 갖는 Choice 모델을 for문으로 쓸 수 있게(iterable) 반환한다. -->



</body>

</html>

Prac1_voting/pracProject/myapp/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>index</title>
</head>

<body>
    <h2>투표하세요</h2>
    {% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li><a href="{% url 'myapp:detail' question.id %}"> {{question.question_text}}</a></li>
        <!--app_name= 'myapp'사용하면 myapp:__ 사용!  -->
        {% endfor %}
    </ul>
    {% endif %}

</body>

</html>

Prac1_voting/pracProject/myapp/templates/result.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>결과</title>
</head>

<body>
    <h1>{{ question.question_text }}</h1>

    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} ---투표수: {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'myapp:detail' question.id %}">Vote again?</a>
</body>

</html>